name: Hackatime Lifetime Stats
on:
  # Schedule updates once a day at midnight
  schedule: [{cron: "0 0 * * *"}]
  # Allows you to manually trigger the workflow at any time
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token stored in repository secrets
          token: ${{ secrets.METRICS_TOKEN }}

          # Core configuration
          base: ""
          template: classic
          filename: github-metrics-hackatime.svg

          # Hackatime / Wakatime Plugin Config
          plugin_wakatime: yes
          plugin_wakatime_sections: time, languages, languages-graphs
          plugin_wakatime_days: 0 # '0' fetches your lifetime accumulated stats
          
          # Replace with your actual Hackatime custom instance URL
          plugin_wakatime_url: https://hackati.me/flighty
